### ISSUE TITLE
Xorg on docker not working due of XAUTHORITY

### ISSUE THREAD

**Issue by glaudiston** [sameersbn/docker-browser-box#1]
On newer Xorg systems your docker don't work.
You need to provide to docker the XAUTH path.

for example:
to tor-browser command work in my michine I need to modify /usr/local/bin/tor-browser
adding:

```
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -
```

And the docker run command look as:

```
docker run -d \
 --cap-add=SYS_ADMIN \
 --env="USER_UID=${USER_UID}" \
 --env="USER_GID=${USER_GID}" \
 --env="DISPLAY=${DISPLAY}" \
 --env="XAUTHORITY=${XAUTH}" \
 --volume=${XSOCK}:${XSOCK} \
 --volume=${XAUTH}:${XAUTH} \
 --volume=/run/user/${USER_UID}/pulse:/run/pulse \
 sameersbn/browser-box:latest $(basename $0) $@ >/dev/null
```

**Comment by sameersbn** [comment]
@glaudiston I have made the changes as you mentioned above. If you find the time please test and let me know if it works.

I am unable to test because I use 14.04
