### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by rarebu** [sameersbn/docker-browser-box#23]
when trying to run the container, i get this error: `install: cannot create regular file '/target/browser-box': Read-only file system`

i used this command: `sudo docker run -it --rm   --volume /usr/local/bin:/target   --env BROWSER_BOX_REPO=sameersbn   sameersbn/browser-box:1.0.1-3 install`

is there a quick workaround or fix?

i would really appreciate if i could get this to work, it would save a ton of time
thanks :)

**Comment by cheealtair** [comment]
When I run according to the instructions -
Run:
docker run  -it --rm  --volume /usr/local/bin:/target   --env BROWSER_BOX_REPO=sameersbn sameersbn/browser-box:1.0.1-3 install

Error:
install: cannot create regular file '/target/browser-box': Permission denied

This may be a slightly different error but still permission related. So I added a few options based on recent docker knowledge I've gotten.  So the result is the below works!

docker run --privileged  -it --rm  --volume /usr/local/bin:/target  -e "container=docker" -v /sys/fs/cgroup:/sys/fs/cgroup -v /tmp/.X11-unix:/tmp/.X11-unix  --env BROWSER_BOX_REPO=sameersbn sameersbn/browser-box:1.0.1-3 install

**Comment by 4volodin** [comment]
I have the same issue, who knows how to solve problem?
when trying to run the container, i get this error: install: cannot create regular file '/target/browser-box': Read-only file system
thx
